version: '3.8'
services:
  express:
    image: node:lts-alpine
    container_name: express
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
        volume:
          nocopy: true
    working_dir: /app
    command: npm start
    ports:
      - '$PORT:$PORT'
    networks:
      - app-network
  #   depends_on:
  #     - mongo
  #
  # mongo:
  #   image: mongo:4.4.1-bionic
  #   container_name: mongo
  #   restart: unless-stopped
  #   env_file: .env
  #   volumes:
  #     - mongodb:/app/mongodb
  #   networks:
  #     - app-network
  #   ports:
  #     - '27017:27017'

volumes:
  node_modules:
  mongodb:

networks:
  app-network:
    driver: bridge
